export enum ReasonCode {
  // Eligibility reason codes
  ELIGIBLE = 'ELIGIBLE',
  MIN_SELECTIONS_NOT_MET = 'MIN_SELECTIONS_NOT_MET',
  MIN_ODDS_NOT_MET = 'MIN_ODDS_NOT_MET',
  MIN_COMBINED_ODDS_NOT_MET = 'MIN_COMBINED_ODDS_NOT_MET',

  // Reward state reason codes
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  REWARD_EXPIRED = 'REWARD_EXPIRED',
  REWARD_ALREADY_USED = 'REWARD_ALREADY_USED',
  NOT_OPTED_IN = 'NOT_OPTED_IN',
  ALREADY_OPTED_IN = 'ALREADY_OPTED_IN',
  RIDE_ENDED = 'RIDE_ENDED',
  RIDE_CRASHED = 'RIDE_CRASHED',

  // Lock reason codes
  BET_ALREADY_LOCKED = 'BET_ALREADY_LOCKED',
  LOCK_NOT_FOUND = 'LOCK_NOT_FOUND',

  // Settlement reason codes
  BET_ALREADY_SETTLED = 'BET_ALREADY_SETTLED',
  INVALID_OUTCOME = 'INVALID_OUTCOME',

  // Profile reason codes
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PROFILE_INACTIVE = 'PROFILE_INACTIVE',
  INVALID_CONFIGURATION = 'INVALID_CONFIGURATION',

  // General errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export type EligibilityReasonCode =
  | ReasonCode.ELIGIBLE
  | ReasonCode.MIN_SELECTIONS_NOT_MET
  | ReasonCode.MIN_ODDS_NOT_MET
  | ReasonCode.MIN_COMBINED_ODDS_NOT_MET
  | ReasonCode.REWARD_NOT_FOUND
  | ReasonCode.REWARD_EXPIRED
  | ReasonCode.REWARD_ALREADY_USED
  | ReasonCode.NOT_OPTED_IN
  | ReasonCode.RIDE_ENDED
  | ReasonCode.RIDE_CRASHED;
